// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTt3GE5QWUiCsvbj69XrDpFm8MuCupvds',
    appId: '1:37536016178:web:d285ddcb414ed41ed7192b',
    messagingSenderId: '37536016178',
    projectId: 'property-app-d9b2e',
    authDomain: 'property-app-d9b2e.firebaseapp.com',
    storageBucket: 'property-app-d9b2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0sd-fcJM9ORvfduT_4LlnOGvmGvtzFM',
    appId: '1:37536016178:android:328c4358a95c3afed7192b',
    messagingSenderId: '37536016178',
    projectId: 'property-app-d9b2e',
    storageBucket: 'property-app-d9b2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc0NMOp59K8vTfk2uKDO7z8RuLJYtKcMc',
    appId: '1:37536016178:ios:9a3ef4d86c2a855cd7192b',
    messagingSenderId: '37536016178',
    projectId: 'property-app-d9b2e',
    storageBucket: 'property-app-d9b2e.firebasestorage.app',
    iosBundleId: 'com.example.propertyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc0NMOp59K8vTfk2uKDO7z8RuLJYtKcMc',
    appId: '1:37536016178:ios:9a3ef4d86c2a855cd7192b',
    messagingSenderId: '37536016178',
    projectId: 'property-app-d9b2e',
    storageBucket: 'property-app-d9b2e.firebasestorage.app',
    iosBundleId: 'com.example.propertyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTt3GE5QWUiCsvbj69XrDpFm8MuCupvds',
    appId: '1:37536016178:web:28bce966da3a703ad7192b',
    messagingSenderId: '37536016178',
    projectId: 'property-app-d9b2e',
    authDomain: 'property-app-d9b2e.firebaseapp.com',
    storageBucket: 'property-app-d9b2e.firebasestorage.app',
  );
}
